backend:
  name: github
  repo: Almutazili/The-Last-Subaltern
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "general"
        label: "General Settings"
        file: "index.html"
        fields:
          - { label: "Publication Name", name: "pub_name", widget: "string", pattern: ['<div class="publication-name">(.*?)</div>', "Publication name"] }
  - name: "articles"
    label: "Articles"
    folder: "_articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
