backend:
  name: github
  repo: Almutazili/The-Last-Subaltern
  branch: main
  base_url: https://the-last-subaltern.naiyergulammustufa.workers.dev

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "site_settings"
    label: "Site Settings"
    files:
      - name: "general"
        label: "General Settings"
        file: "index.html"
        fields:
          - { label: "Publication Name", name: "pub_name", widget: "string", pattern: ['<div class="publication-name">(.*?)</div>', "Publication name"] }
